CREATE TABLE board.BOARD (
	ID BIGINT UNSIGNED auto_increment NOT NULL,
	TITLE varchar(100) NOT NULL,
	CONTENT varchar(5000) NOT NULL,
	AUTHOR varchar(100) NOT NULL,
	CREATED_AT DATETIME DEFAULT NOW() NOT NULL,
	UPDATED_AT DATETIME NULL,
	DELETED_AT DATETIME NULL,
	CONSTRAINT BOARD_PK PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE board.user (
	username varchar(100) NOT NULL,
	password varchar(200) NOT NULL,
	created_at DATETIME NOT NULL,
	deleted_at DATETIME NULL,
	CONSTRAINT auth_pk PRIMARY KEY (username)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;