drop table reply ;
drop table board ;
drop table user ;

-- board.user definition
CREATE TABLE board.user (
	ID BIGINT UNSIGNED auto_increment NOT NULL,
	username varchar(100) NOT NULL,
	password varchar(200) NOT NULL,
	created_at DATETIME NOT NULL,
	deleted_at DATETIME NULL,
	CONSTRAINT auth_pk PRIMARY KEY (ID),
	CONSTRAINT auth_uq UNIQUE (username)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- board.board definition
CREATE TABLE board.BOARD (
	ID BIGINT UNSIGNED auto_increment NOT NULL,
	TITLE varchar(100) NOT NULL,
	CONTENT varchar(5000) NOT NULL,
	USER_ID BIGINT UNSIGNED NOT NULL,
	CREATED_AT DATETIME DEFAULT NOW() NOT NULL,
	UPDATED_AT DATETIME NULL,
	DELETED_AT DATETIME NULL,
	CONSTRAINT BOARD_PK PRIMARY KEY (ID),
	FOREIGN KEY (USER_ID) references board.user(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;



-- board.reply definition
CREATE TABLE board.reply (
	ID BIGINT UNSIGNED auto_increment NOT NULL,
	BOARD_ID BIGINT UNSIGNED NOT NULL,
	USER_ID BIGINT UNSIGNED NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	CREATED_AT DATETIME DEFAULT NOW() NOT NULL,
	UPDATED_AT DATETIME NULL,
	DELETED_AT varchar(100) NULL,
	CONSTRAINT reply_pk PRIMARY KEY (ID),
	FOREIGN KEY (BOARD_ID) REFERENCES board.board(ID),
	FOREIGN KEY (USER_ID) REFERENCES board.user(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;